language: ruby
rvm:
- 2.3.0
install:
- curl -O https://s3-us-west-2.amazonaws.com/screener-files/ci/v2.1/screener-ci.zip
- unzip -o screener-ci.zip
- gem install bundler
- bundle install
before_script:
- curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip > ngrok.zip
- unzip ngrok.zip
- "./ngrok http 3000 > /dev/null &"
- sleep 5
- NGROK_URL=$(curl -s localhost:4040/api/tunnels/command_line | jq --raw-output .public_url)
after_script: "-./screener-ci.sh $SCREENER_API_KEY $SCREENER_GROUP $BUILD_NUMBER --repo
  $GITHUB_REPO_SLUG --commit $GITHUB_COMMIT_SHA"
env:
  global:
  - secure: fwF5f/Ia7OWdJgqHeGGSBOCPaKuaYHiUvjUtec/cUglbNfq/HlUdHOkjGXFEF0lNABlqnzzvXaIM40c+NLzBgd15vYmWHiTWCGHIu8Awk5TONMJEZsqyaDPvQdzFH+7zrvxBvvCLJjKThYXVedjl6SfPBnchXMp3MVeZTByNj4u9pjBGLZcgafN3wyap1yUwgW6h+rgA2Hkz3IctqowM/YNoZGz3egMQSaRZrFw4iiHy3UiQb6G8s3CZ6goE4/E2xEiRtlmV+heoDpPr0rruAsyjEWg7LH91s8JJ3wFq4YsFLYenUiG5qEWxJmjH2qhgrnljpBfWjDhgh9Ik3L9AsdrN5jhHNJaPJYDdOVuPaZHDSds84PBSESgnsm5nTHeH2qp7g2bD7hgncgIjv9ZXzNP96DghDRcG6nuz4ppN0IjThFbEUCZFHSWtUYeHMVhoALlOjMIwYg9l8F128/lqPN1P49FUoshql88+aPzp7MERvOB36xjld5dmWQTgSvxo5iJpM7non4pu6N3tVwdRHbwCqBQWVW0F/+PcvHCHVWlhSOczfGAODti8ucKcw/TdUYWsR8apBXJMGKUNbDQ2ydqDKNRVNWqnLt8vLSZe55eoqErwiMnkOYdq69VUaQu7qr6AVN7gvZvjLlGyYA3kBET0YD7Gja/by771NxXguwI=
  - secure: dIQiKPZ/tWDV2FLUDU6FwJKOnLGMu+fJPR3RpArugLha3G3V+4L3g6yNKyN4GrsZIGuttaX83af4dgegbdIB5qMsRyGmoDxr/a6QuQ6afBRReeYcK7zL/qD2aNkrryeRuxqqudij5rDP80X9/tDA7vbh5q8/stv9SguzBAzNkI8hKvFwswcCc84/ozvWaU8aXjTilZw/WSixMcZSfNZCcf1pxxflwOTUhxRBrAeJ+C1bxTEFr+PLlCc7JevOPzoTWw8Asc86hf0a+jUzdbMG8AGHyCihFCY0u+zfUakzK4eAwIgShWyPgWWPH6zpW321eB6TrN+++sSgHNmpg9wm4MmgW7RsL7B+CtZ2rZmCT+sI5yvjFYbYqjyCR0ukNrP1UfM11JqvxwRpdf/tUDfKCiNJhS3EBL8jNsan4iv8kLA8LZsjjpO0T1NYOw9b/jvFtQE0kxMM1kGmA2tVPC5u41aAid7VRYU8C2gDkydaMoA1Xaqe8kYZJmAICAOqRLqjMwq9RX03fAKd9piXTJDLtQshk4sTqYNu7oatOT/Fv80eBpCLS9nZEiutpI7ik4JrIkZlAs6pWWm+u03ndB92nrM3VVuBnv+GxYHmTTY5bRakkS5/XpCr7e17fXYvxELPENv9PZwoN9V+SKUwx7lfbeIVjlu7b3a5znfbp4eVa+k=
