language: ruby
rvm:
  - 2.3.0

before_script:
  - curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip > ngrok.zip
  - unzip ngrok.zip
  - ./ngrok http 3000 > /dev/null &
  - sleep 2
  - NGROK_URL=$(curl -s localhost:4040/api/tunnels/command_line | jq --raw-output .public_url)