name: CI

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: CultureHQ/actions-bundler@master
    - args: install
    - uses: actions/checkout@v1
    - name: Build and test
      run: |
        rspec specs/functional/index.spec
